#!/bin/bash
#
# moncli      Start/Stop Moncli.
#
# chkconfig: - 62 38
# description: Moncli is a metric transport and evaluation daemon.
#
# processname: moncli
#
# By: Jelle Smet
#
#
# 

# Source function library
#. /etc/init.d/functions

# Get network config
#. /etc/sysconfig/network

PYTHON_EXEC='/usr/bin/python'
MONCLI_EXEC='/opt/moncli/bin/moncli'
RETVAL=0

start() {
    echo -n $"Starting Moncli: " 
    # Start me up!
    $PYTHON_EXEC $MONCLI_EXEC start --host besrvup-sss01 --local_repo /opt/moncli/lib/repository --cache /opt/moncli/var/moncli.cache --pid /opt/moncli/var/moncli.pid
    RETVAL=$?
    echo
    return $RETVAL
}

stop() {
    echo -n $"Stopping Moncli: " 
    $PYTHON_EXEC $MONCLI_EXEC stop --host besrvup-sss01 --local_repo /opt/moncli/lib/repository --cache /opt/moncli/var/moncli.cache --pid /opt/moncli/var/moncli.pid
    return $RETVAL
}    

restart() {
      stop
    start
}    

reload() {
    stop
    start
}

case "$1" in
  start)
      start
    ;;
  stop)
      stop
    ;;
  status)
    status instiki
    ;;
  restart)
      restart
    ;;
  reload)
    reload
    ;;
  *)
    echo $"Usage: $0 {start|stop|status|restart|reload}" 
    exit 1
esac

exit $?
